### ISSUE TITLE
Criar botão para exportar o Json do Veículo

### ISSUE THREAD

**Issue by GustavoHennig** [felipeeC/TelaAdicionarRemoverAtualizar#6]
- O botão deve ficar onde a implementação for mais fácil;
- O botão pode/deve exibir o Json em uma nova Janela para que o texto possa ser copiado;
- O Json deve conter todos atributos do veículo e também a lista de pessoas vinculadas a ele.

**Comment by felipeeC** [comment]
criado botão exportar para json, agora falta atribuir os dados de pessoas

**Comment by felipeeC** [comment]
criado botão e tela para mostrar json
